-- DMS user keybind overrides (edit via Control Center or dms; do not remove this header)

hl.unbind("SUPER + ALT + CTRL + S")
hl.bind("SUPER + ALT + CTRL + S", hl.dsp.exec_cmd("dms screenshot"), { description = "dms screenshot" })
hl.unbind("SUPER + SHIFT + Escape")
hl.bind("SUPER + SHIFT + Escape", hl.dsp.exec_cmd("dms ipc call powermenu toggle"), { description = "Power Menu: Toggle" })
hl.unbind("SUPER + C")
hl.bind("SUPER + C", hl.dsp.window.center(), { description = "Center Window" })
hl.unbind("SUPER + ALT + CTRL + B")
hl.bind("SUPER + ALT + CTRL + B", hl.dsp.exec_cmd("zen-browser"), { description = "Zen Browser" })
hl.unbind("SUPER + ALT + CTRL + C")
hl.bind("SUPER + ALT + CTRL + C", hl.dsp.exec_cmd("zeditor"), { description = "Zed" })
hl.unbind("SUPER + ALT + CTRL + D")
hl.bind("SUPER + ALT + CTRL + D", hl.dsp.exec_cmd("discord"), { description = "Discord" })
hl.unbind("SUPER + ALT + CTRL + F")
hl.bind("SUPER + ALT + CTRL + F", hl.dsp.exec_cmd("nautilus"), { description = "Nautilus" })
hl.unbind("SUPER + ALT + CTRL + Slash")
hl.bind("SUPER + ALT + CTRL + Slash", hl.dsp.exec_cmd("proton-pass"), { description = "Proton Pass" })
hl.unbind("SUPER + ALT + CTRL + T")
hl.bind("SUPER + ALT + CTRL + T", hl.dsp.exec_cmd("ghostty"), { description = "Ghostty" })
hl.unbind("ALT + Print")
hl.unbind("CTRL + Print")
hl.unbind("CTRL + SHIFT + D")
hl.bind("CTRL + SHIFT + D", hl.dsp.pass({ window = "class:^(discord)$" }), { description = "Toggle Discord Deafen" })
hl.unbind("CTRL + SHIFT + M")
hl.bind("CTRL + SHIFT + M", hl.dsp.pass({ window = "class:^(discord)$" }), { description = "Toggle Discord Mute" })
hl.unbind("Print")
hl.unbind("SUPER + CTRL + F")
hl.unbind("SUPER + CTRL + J")
hl.unbind("SUPER + CTRL + K")
hl.unbind("SUPER + CTRL + M")
hl.unbind("SUPER + CTRL + down")
hl.unbind("SUPER + End")
hl.unbind("SUPER + Home")
hl.unbind("SUPER + M")
hl.unbind("SUPER + O")
hl.unbind("SUPER + P")
hl.unbind("SUPER + Q")
hl.bind("SUPER + Q", hl.dsp.window.kill(), { description = "Force Kill Window" })
hl.unbind("SUPER + SHIFT + CTRL + H")
hl.unbind("SUPER + SHIFT + CTRL + J")
hl.unbind("SUPER + SHIFT + CTRL + K")
hl.unbind("SUPER + SHIFT + CTRL + L")
hl.unbind("SUPER + SHIFT + CTRL + down")
hl.unbind("SUPER + SHIFT + CTRL + left")
hl.unbind("SUPER + SHIFT + CTRL + right")
hl.unbind("SUPER + SHIFT + CTRL + up")
hl.unbind("SUPER + SHIFT + E")
hl.unbind("SUPER + SHIFT + P")
hl.unbind("SUPER + SHIFT + Page_Down")
hl.unbind("SUPER + SHIFT + equal")
hl.unbind("SUPER + SHIFT + minus")
hl.unbind("SUPER + T")
hl.unbind("SUPER + W")
hl.bind("SUPER + W", hl.dsp.window.close(), { description = "Close Window" })
hl.unbind("SUPER + X")
