-- Auto-generated by DMS — do not edit manually

hl.monitor({ output = "", mode = "preferred", position = "3840x0", scale = 1 })
hl.monitor({ output = "DP-1", mode = "3840x2160@143.988", position = "3072x0", scale = 1.25, vrr = 0 })
hl.monitor({ output = "HDMI-A-1", mode = "3840x2160@143.988", position = "0x0", scale = 1.25, vrr = 0 })
