-- Auto-generated by DMS Matugen hook — do not edit manually.
-- Remove require("dms.colors") from hyprland.lua to override.

hl.config({
	general = {
		col = {
			active_border = "rgb(a7c080)",
			inactive_border = "rgb(56635f)",
		},
	},
	group = {
		col = {
			border_active = "rgb(a7c080)",
			border_inactive = "rgb(56635f)",
			border_locked_active = "rgb(e57e80)",
			border_locked_inactive = "rgb(56635f)",
		},
		groupbar = {
			col = {
				active = "rgb(a7c080)",
				inactive = "rgb(56635f)",
				locked_active = "rgb(e57e80)",
				locked_inactive = "rgb(56635f)",
			},
		},
	},
})
