# Refer to https://wiki.hyprland.org/Configuring/Variables/

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    gaps_in = 5
    gaps_out = 5

    border_size = 2
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    rounding = 5
}
